// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ASCREALTIMEDATA_ODB_HXX
#define ASCREALTIMEDATA_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "ascrealtimedata.h"

#include "emerealtimedata-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // ascrealtimedata
  //
  template <>
  struct class_traits< ::ascrealtimedata >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::ascrealtimedata >
  {
    public:
    typedef ::ascrealtimedata object_type;
    typedef ::ascrealtimedata* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef object_traits< ::emerealtimedata >::id_type id_type;

    static const bool auto_id = object_traits< ::emerealtimedata >::auto_id;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // ascrealtimedata
  //
  template <typename A>
  struct query_columns< ::ascrealtimedata, id_pgsql, A >:
    query_columns< ::emerealtimedata, id_pgsql, A >
  {
    // emerealtimedata
    //
    typedef query_columns< ::emerealtimedata, id_pgsql, A > emerealtimedata;

    // shutterspeed
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    shutterspeed_type_;

    static const shutterspeed_type_ shutterspeed;

    // aperture
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    aperture_type_;

    static const aperture_type_ aperture;

    // iso
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    iso_type_;

    static const iso_type_ iso;

    // jpeg
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    jpeg_type_;

    static const jpeg_type_ jpeg;

    // raw
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    raw_type_;

    static const raw_type_ raw;

    // fits
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    fits_type_;

    static const fits_type_ fits;
  };

  template <typename A>
  const typename query_columns< ::ascrealtimedata, id_pgsql, A >::shutterspeed_type_
  query_columns< ::ascrealtimedata, id_pgsql, A >::
  shutterspeed (A::table_name, "\"shutterspeed\"", 0);

  template <typename A>
  const typename query_columns< ::ascrealtimedata, id_pgsql, A >::aperture_type_
  query_columns< ::ascrealtimedata, id_pgsql, A >::
  aperture (A::table_name, "\"aperture\"", 0);

  template <typename A>
  const typename query_columns< ::ascrealtimedata, id_pgsql, A >::iso_type_
  query_columns< ::ascrealtimedata, id_pgsql, A >::
  iso (A::table_name, "\"iso\"", 0);

  template <typename A>
  const typename query_columns< ::ascrealtimedata, id_pgsql, A >::jpeg_type_
  query_columns< ::ascrealtimedata, id_pgsql, A >::
  jpeg (A::table_name, "\"jpeg\"", 0);

  template <typename A>
  const typename query_columns< ::ascrealtimedata, id_pgsql, A >::raw_type_
  query_columns< ::ascrealtimedata, id_pgsql, A >::
  raw (A::table_name, "\"raw\"", 0);

  template <typename A>
  const typename query_columns< ::ascrealtimedata, id_pgsql, A >::fits_type_
  query_columns< ::ascrealtimedata, id_pgsql, A >::
  fits (A::table_name, "\"fits\"", 0);

  template <typename A>
  struct pointer_query_columns< ::ascrealtimedata, id_pgsql, A >:
    query_columns< ::ascrealtimedata, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::ascrealtimedata, id_pgsql >:
    public access::object_traits< ::ascrealtimedata >
  {
    public:
    typedef object_traits_impl< ::emerealtimedata, id_pgsql >::id_image_type id_image_type;

    struct image_type: object_traits_impl< ::emerealtimedata, id_pgsql >::image_type
    {
      // _shutterspeed
      //
      double _shutterspeed_value;
      bool _shutterspeed_null;

      // _aperture
      //
      double _aperture_value;
      bool _aperture_null;

      // _iso
      //
      short _iso_value;
      bool _iso_null;

      // _jpeg
      //
      short _jpeg_value;
      bool _jpeg_null;

      // _raw
      //
      short _raw_value;
      bool _raw_null;

      // _fits
      //
      short _fits_value;
      bool _fits_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::ascrealtimedata, id_common >:
    public access::object_traits_impl< ::ascrealtimedata, id_pgsql >
  {
  };

  // ascrealtimedata
  //
}

#include "ascrealtimedata-odb.ixx"

#include <odb/post.hxx>

#endif // ASCREALTIMEDATA_ODB_HXX
