// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef AT60SLAVEDOMESTATUS_ODB_HXX
#define AT60SLAVEDOMESTATUS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "at60slavedomestatus.h"

#include "atccspublicstatus-odb.hxx"
#include "atccsslavedomestatus-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // at60slavedomestatus
  //
  template <>
  struct class_traits< ::at60slavedomestatus >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::at60slavedomestatus >
  {
    public:
    typedef ::at60slavedomestatus object_type;
    typedef ::at60slavedomestatus* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef object_traits< ::atccspublicstatus >::id_type id_type;

    static const bool auto_id = object_traits< ::atccspublicstatus >::auto_id;

    static const bool abstract = true;

    static id_type
    id (const object_type&);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // at60slavedomestatus
  //
  template <typename A>
  struct query_columns< ::at60slavedomestatus, id_pgsql, A >:
    query_columns< ::atccsslavedomestatus, id_pgsql, A >
  {
    // atccsslavedomestatus
    //
    typedef query_columns< ::atccsslavedomestatus, id_pgsql, A > atccsslavedomestatus;
  };

  template <typename A>
  struct pointer_query_columns< ::at60slavedomestatus, id_pgsql, A >:
    query_columns< ::at60slavedomestatus, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::at60slavedomestatus, id_pgsql >:
    public access::object_traits< ::at60slavedomestatus >
  {
    public:
    typedef object_traits_impl< ::atccspublicstatus, id_pgsql >::id_image_type id_image_type;

    struct image_type: object_traits_impl< ::atccsslavedomestatus, id_pgsql >::image_type
    {
    };

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);
  };

  // at60slavedomestatus
  //
}

#include "at60slavedomestatus-odb.ixx"

#include <odb/post.hxx>

#endif // AT60SLAVEDOMESTATUS_ODB_HXX
