// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // atccspublicstatus
  //

  inline
  access::object_traits< ::atccspublicstatus >::id_type
  access::object_traits< ::atccspublicstatus >::
  id (const object_type& o)
  {
    return o._id;
  }
}

namespace odb
{
  // atccspublicstatus
  //
}

