// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "atccsoccupation-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // atccsoccupation
  //

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  persist_statement_name[] = "persist_atccsoccupation";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  find_statement_name[] = "find_atccsoccupation";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  update_statement_name[] = "update_atccsoccupation";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  erase_statement_name[] = "erase_atccsoccupation";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  query_statement_name[] = "query_atccsoccupation";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  erase_query_statement_name[] = "erase_query_atccsoccupation";

  const unsigned int access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int2_oid,
    pgsql::int2_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int2_oid,
    pgsql::int2_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid
  };

  struct access::object_traits_impl< ::atccsoccupation, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::atccsoccupation, id_pgsql >::id_type
  access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::atccsoccupation, id_pgsql >::id_type
  access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _id
    //
    t[0UL] = 0;

    // _user
    //
    t[1UL] = 0;

    // _at
    //
    t[2UL] = 0;

    // _occupation
    //
    t[3UL] = 0;

    // _start
    //
    t[4UL] = 0;

    // _end
    //
    t[5UL] = 0;

    // _priority
    //
    t[6UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // _id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _user
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._user_value;
    b[n].is_null = &i._user_null;
    n++;

    // _at
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i._at_value;
    b[n].is_null = &i._at_null;
    n++;

    // _occupation
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i._occupation_value;
    b[n].is_null = &i._occupation_null;
    n++;

    // _start
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._start_value;
    b[n].is_null = &i._start_null;
    n++;

    // _end
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._end_value;
    b[n].is_null = &i._end_null;
    n++;

    // _priority
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._priority_value;
    b[n].is_null = &i._priority_null;
    n++;
  }

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // _user
    //
    {
      unsigned int const& v =
        o._user;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._user_value, is_null, v);
      i._user_null = is_null;
    }

    // _at
    //
    {
      short unsigned int const& v =
        o._at;

      bool is_null (false);
      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_image (
        i._at_value, is_null, v);
      i._at_null = is_null;
    }

    // _occupation
    //
    {
      short unsigned int const& v =
        o._occupation;

      bool is_null (false);
      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_image (
        i._occupation_value, is_null, v);
      i._occupation_null = is_null;
    }

    // _start
    //
    {
      unsigned int const& v =
        o._start;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._start_value, is_null, v);
      i._start_null = is_null;
    }

    // _end
    //
    {
      unsigned int const& v =
        o._end;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._end_value, is_null, v);
      i._end_null = is_null;
    }

    // _priority
    //
    {
      unsigned int const& v =
        o._priority;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._priority_value, is_null, v);
      i._priority_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _user
    //
    {
      unsigned int& v =
        o._user;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._user_value,
        i._user_null);
    }

    // _at
    //
    {
      short unsigned int& v =
        o._at;

      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_value (
        v,
        i._at_value,
        i._at_null);
    }

    // _occupation
    //
    {
      short unsigned int& v =
        o._occupation;

      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_value (
        v,
        i._occupation_value,
        i._occupation_null);
    }

    // _start
    //
    {
      unsigned int& v =
        o._start;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._start_value,
        i._start_null);
    }

    // _end
    //
    {
      unsigned int& v =
        o._end;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._end_value,
        i._end_null);
    }

    // _priority
    //
    {
      unsigned int& v =
        o._priority;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._priority_value,
        i._priority_null);
    }
  }

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::persist_statement[] =
  "INSERT INTO \"atccsoccupation\" "
  "(\"id\", "
  "\"user\", "
  "\"at\", "
  "\"occupation\", "
  "\"start\", "
  "\"end\", "
  "\"priority\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::find_statement[] =
  "SELECT "
  "\"atccsoccupation\".\"id\", "
  "\"atccsoccupation\".\"user\", "
  "\"atccsoccupation\".\"at\", "
  "\"atccsoccupation\".\"occupation\", "
  "\"atccsoccupation\".\"start\", "
  "\"atccsoccupation\".\"end\", "
  "\"atccsoccupation\".\"priority\" "
  "FROM \"atccsoccupation\" "
  "WHERE \"atccsoccupation\".\"id\"=$1";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::update_statement[] =
  "UPDATE \"atccsoccupation\" "
  "SET "
  "\"user\"=$1, "
  "\"at\"=$2, "
  "\"occupation\"=$3, "
  "\"start\"=$4, "
  "\"end\"=$5, "
  "\"priority\"=$6 "
  "WHERE \"id\"=$7";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::erase_statement[] =
  "DELETE FROM \"atccsoccupation\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::query_statement[] =
  "SELECT "
  "\"atccsoccupation\".\"id\", "
  "\"atccsoccupation\".\"user\", "
  "\"atccsoccupation\".\"at\", "
  "\"atccsoccupation\".\"occupation\", "
  "\"atccsoccupation\".\"start\", "
  "\"atccsoccupation\".\"end\", "
  "\"atccsoccupation\".\"priority\" "
  "FROM \"atccsoccupation\"";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"atccsoccupation\"";

  const char access::object_traits_impl< ::atccsoccupation, id_pgsql >::table_name[] =
  "\"atccsoccupation\"";

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj._id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::atccsoccupation, id_pgsql >::pointer_type
  access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::atccsoccupation, id_pgsql >::object_type >
  access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::atccsoccupation, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"atccsoccupation\" CASCADE");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"atccsoccupation\" (\n"
                      "  \"id\" SERIAL NOT NULL PRIMARY KEY,\n"
                      "  \"user\" INTEGER NOT NULL,\n"
                      "  \"at\" SMALLINT NOT NULL,\n"
                      "  \"occupation\" SMALLINT NOT NULL,\n"
                      "  \"start\" INTEGER NOT NULL,\n"
                      "  \"end\" INTEGER NOT NULL,\n"
                      "  \"priority\" INTEGER NOT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_pgsql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
