// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "atccsinstruction-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // atccsinstruction
  //

  access::object_traits_impl< ::atccsinstruction, id_pgsql >::id_type
  access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::atccsinstruction, id_pgsql >::id_type
  access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _id
    //
    t[0UL] = 0;

    // _sec
    //
    t[1UL] = 0;

    // _msec
    //
    t[2UL] = 0;

    // _user
    //
    t[3UL] = 0;

    // _at
    //
    t[4UL] = 0;

    // _device
    //
    t[5UL] = 0;

    // _sequence
    //
    t[6UL] = 0;

    // _timeout
    //
    t[7UL] = 0;

    // _plan
    //
    t[8UL] = 0;

    // _instruction
    //
    t[9UL] = 0;

    // _param
    //
    if (t[10UL])
    {
      i._param_value.capacity (i._param_size);
      grew = true;
    }

    // _result
    //
    t[11UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // _id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _sec
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._sec_value;
    b[n].is_null = &i._sec_null;
    n++;

    // _msec
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._msec_value;
    b[n].is_null = &i._msec_null;
    n++;

    // _user
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._user_value;
    b[n].is_null = &i._user_null;
    n++;

    // _at
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i._at_value;
    b[n].is_null = &i._at_null;
    n++;

    // _device
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i._device_value;
    b[n].is_null = &i._device_null;
    n++;

    // _sequence
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._sequence_value;
    b[n].is_null = &i._sequence_null;
    n++;

    // _timeout
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._timeout_value;
    b[n].is_null = &i._timeout_null;
    n++;

    // _plan
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._plan_value;
    b[n].is_null = &i._plan_null;
    n++;

    // _instruction
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._instruction_value;
    b[n].is_null = &i._instruction_null;
    n++;

    // _param
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i._param_value.data ();
    b[n].capacity = i._param_value.capacity ();
    b[n].size = &i._param_size;
    b[n].is_null = &i._param_null;
    n++;

    // _result
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._result_value;
    b[n].is_null = &i._result_null;
    n++;
  }

  void access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // _sec
    //
    {
      unsigned int const& v =
        o._sec;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._sec_value, is_null, v);
      i._sec_null = is_null;
    }

    // _msec
    //
    {
      unsigned int const& v =
        o._msec;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._msec_value, is_null, v);
      i._msec_null = is_null;
    }

    // _user
    //
    {
      unsigned int const& v =
        o._user;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._user_value, is_null, v);
      i._user_null = is_null;
    }

    // _at
    //
    {
      short unsigned int const& v =
        o._at;

      bool is_null (false);
      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_image (
        i._at_value, is_null, v);
      i._at_null = is_null;
    }

    // _device
    //
    {
      short unsigned int const& v =
        o._device;

      bool is_null (false);
      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_image (
        i._device_value, is_null, v);
      i._device_null = is_null;
    }

    // _sequence
    //
    {
      unsigned int const& v =
        o._sequence;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._sequence_value, is_null, v);
      i._sequence_null = is_null;
    }

    // _timeout
    //
    {
      unsigned int const& v =
        o._timeout;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._timeout_value, is_null, v);
      i._timeout_null = is_null;
    }

    // _plan
    //
    {
      unsigned int const& v =
        o._plan;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._plan_value, is_null, v);
      i._plan_null = is_null;
    }

    // _instruction
    //
    {
      unsigned int const& v =
        o._instruction;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._instruction_value, is_null, v);
      i._instruction_null = is_null;
    }

    // _param
    //
    {
      ::std::string const& v =
        o._param;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._param_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i._param_value,
        size,
        is_null,
        v);
      i._param_null = is_null;
      i._param_size = size;
      grew = grew || (cap != i._param_value.capacity ());
    }

    // _result
    //
    {
      unsigned int const& v =
        o._result;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._result_value, is_null, v);
      i._result_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _id
    //
    {
      long long unsigned int& v =
        o._id;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _sec
    //
    {
      unsigned int& v =
        o._sec;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._sec_value,
        i._sec_null);
    }

    // _msec
    //
    {
      unsigned int& v =
        o._msec;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._msec_value,
        i._msec_null);
    }

    // _user
    //
    {
      unsigned int& v =
        o._user;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._user_value,
        i._user_null);
    }

    // _at
    //
    {
      short unsigned int& v =
        o._at;

      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_value (
        v,
        i._at_value,
        i._at_null);
    }

    // _device
    //
    {
      short unsigned int& v =
        o._device;

      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_value (
        v,
        i._device_value,
        i._device_null);
    }

    // _sequence
    //
    {
      unsigned int& v =
        o._sequence;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._sequence_value,
        i._sequence_null);
    }

    // _timeout
    //
    {
      unsigned int& v =
        o._timeout;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._timeout_value,
        i._timeout_null);
    }

    // _plan
    //
    {
      unsigned int& v =
        o._plan;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._plan_value,
        i._plan_null);
    }

    // _instruction
    //
    {
      unsigned int& v =
        o._instruction;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._instruction_value,
        i._instruction_null);
    }

    // _param
    //
    {
      ::std::string& v =
        o._param;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i._param_value,
        i._param_size,
        i._param_null);
    }

    // _result
    //
    {
      unsigned int& v =
        o._result;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._result_value,
        i._result_null);
    }
  }

  void access::object_traits_impl< ::atccsinstruction, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }
}

#include <odb/post.hxx>
