/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "atccsplan" CASCADE;

CREATE TABLE "atccsplan" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "user" TEXT NOT NULL,
  "project" TEXT NOT NULL,
  "target" TEXT NOT NULL,
  "filter" TEXT NOT NULL,
  "sec" INTEGER NOT NULL,
  "msec" INTEGER NOT NULL,
  "result" INTEGER NOT NULL,
  "percent" INTEGER NOT NULL,
  "at" INTEGER NOT NULL,
  "type" INTEGER NOT NULL,
  "epoch" INTEGER NOT NULL,
  "exposureCount" INTEGER NOT NULL,
  "gain" INTEGER NOT NULL,
  "bin" INTEGER NOT NULL,
  "readout" INTEGER NOT NULL,
  "exposureTime" DOUBLE PRECISION NOT NULL,
  "rightAscension" DOUBLE PRECISION NOT NULL,
  "declination" DOUBLE PRECISION NOT NULL,
  "delayTime" DOUBLE PRECISION NOT NULL);

