// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "atccsutilization-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // atccsutilization
  //

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::
  persist_statement_name[] = "persist_atccsutilization";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::
  find_statement_name[] = "find_atccsutilization";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::
  update_statement_name[] = "update_atccsutilization";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::
  erase_statement_name[] = "erase_atccsutilization";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::
  query_statement_name[] = "query_atccsutilization";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::
  erase_query_statement_name[] = "erase_query_atccsutilization";

  const unsigned int access::object_traits_impl< ::atccsutilization, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::atccsutilization, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::atccsutilization, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::int4_oid
  };

  struct access::object_traits_impl< ::atccsutilization, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::atccsutilization, id_pgsql >::id_type
  access::object_traits_impl< ::atccsutilization, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i._at_value,
        i._at_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::atccsutilization, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _at
    //
    t[0UL] = 0;

    // _start
    //
    t[1UL] = 0;

    // _end
    //
    t[2UL] = 0;

    // _user
    //
    t[3UL] = 0;

    // _plan
    //
    t[4UL] = 0;

    // _priority
    //
    t[5UL] = 0;

    // _descirption
    //
    if (t[6UL])
    {
      i._descirption_value.capacity (i._descirption_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // _at
    //
    if (sk != statement_update)
    {
      b[n].type = pgsql::bind::integer;
      b[n].buffer = &i._at_value;
      b[n].is_null = &i._at_null;
      n++;
    }

    // _start
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._start_value;
    b[n].is_null = &i._start_null;
    n++;

    // _end
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._end_value;
    b[n].is_null = &i._end_null;
    n++;

    // _user
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._user_value;
    b[n].is_null = &i._user_null;
    n++;

    // _plan
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._plan_value;
    b[n].is_null = &i._plan_null;
    n++;

    // _priority
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i._priority_value;
    b[n].is_null = &i._priority_null;
    n++;

    // _descirption
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i._descirption_value.data ();
    b[n].capacity = i._descirption_value.capacity ();
    b[n].size = &i._descirption_size;
    b[n].is_null = &i._descirption_null;
    n++;
  }

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::atccsutilization, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // _at
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._at;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._at_value, is_null, v);
      i._at_null = is_null;
    }

    // _start
    //
    {
      unsigned int const& v =
        o._start;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._start_value, is_null, v);
      i._start_null = is_null;
    }

    // _end
    //
    {
      unsigned int const& v =
        o._end;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._end_value, is_null, v);
      i._end_null = is_null;
    }

    // _user
    //
    {
      unsigned int const& v =
        o._user;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._user_value, is_null, v);
      i._user_null = is_null;
    }

    // _plan
    //
    {
      unsigned int const& v =
        o._plan;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._plan_value, is_null, v);
      i._plan_null = is_null;
    }

    // _priority
    //
    {
      unsigned int const& v =
        o._priority;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i._priority_value, is_null, v);
      i._priority_null = is_null;
    }

    // _descirption
    //
    {
      ::std::string const& v =
        o._descirption;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._descirption_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i._descirption_value,
        size,
        is_null,
        v);
      i._descirption_null = is_null;
      i._descirption_size = size;
      grew = grew || (cap != i._descirption_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _at
    //
    {
      unsigned int& v =
        o._at;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._at_value,
        i._at_null);
    }

    // _start
    //
    {
      unsigned int& v =
        o._start;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._start_value,
        i._start_null);
    }

    // _end
    //
    {
      unsigned int& v =
        o._end;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._end_value,
        i._end_null);
    }

    // _user
    //
    {
      unsigned int& v =
        o._user;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._user_value,
        i._user_null);
    }

    // _plan
    //
    {
      unsigned int& v =
        o._plan;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._plan_value,
        i._plan_null);
    }

    // _priority
    //
    {
      unsigned int& v =
        o._priority;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i._priority_value,
        i._priority_null);
    }

    // _descirption
    //
    {
      ::std::string& v =
        o._descirption;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i._descirption_value,
        i._descirption_size,
        i._descirption_null);
    }
  }

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::persist_statement[] =
  "INSERT INTO \"atccsutilization\" "
  "(\"at\", "
  "\"start\", "
  "\"end\", "
  "\"user\", "
  "\"plan\", "
  "\"priority\", "
  "\"descirption\") "
  "VALUES "
  "($1, $2, $3, $4, $5, $6, $7)";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::find_statement[] =
  "SELECT "
  "\"atccsutilization\".\"at\", "
  "\"atccsutilization\".\"start\", "
  "\"atccsutilization\".\"end\", "
  "\"atccsutilization\".\"user\", "
  "\"atccsutilization\".\"plan\", "
  "\"atccsutilization\".\"priority\", "
  "\"atccsutilization\".\"descirption\" "
  "FROM \"atccsutilization\" "
  "WHERE \"atccsutilization\".\"at\"=$1";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::update_statement[] =
  "UPDATE \"atccsutilization\" "
  "SET "
  "\"start\"=$1, "
  "\"end\"=$2, "
  "\"user\"=$3, "
  "\"plan\"=$4, "
  "\"priority\"=$5, "
  "\"descirption\"=$6 "
  "WHERE \"at\"=$7";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::erase_statement[] =
  "DELETE FROM \"atccsutilization\" "
  "WHERE \"at\"=$1";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::query_statement[] =
  "SELECT "
  "\"atccsutilization\".\"at\", "
  "\"atccsutilization\".\"start\", "
  "\"atccsutilization\".\"end\", "
  "\"atccsutilization\".\"user\", "
  "\"atccsutilization\".\"plan\", "
  "\"atccsutilization\".\"priority\", "
  "\"atccsutilization\".\"descirption\" "
  "FROM \"atccsutilization\"";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"atccsutilization\"";

  const char access::object_traits_impl< ::atccsutilization, id_pgsql >::table_name[] =
  "\"atccsutilization\"";

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._at);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::atccsutilization, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  bool access::object_traits_impl< ::atccsutilization, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::atccsutilization, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._at);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::atccsutilization, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::atccsutilization, id_pgsql >::object_type >
  access::object_traits_impl< ::atccsutilization, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::atccsutilization, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"atccsutilization\" CASCADE");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"atccsutilization\" (\n"
                      "  \"at\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"start\" INTEGER NOT NULL,\n"
                      "  \"end\" INTEGER NOT NULL,\n"
                      "  \"user\" INTEGER NOT NULL,\n"
                      "  \"plan\" INTEGER NOT NULL,\n"
                      "  \"priority\" INTEGER NOT NULL,\n"
                      "  \"descirption\" TEXT NOT NULL)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_pgsql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
