// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb
{
  // atccsinstruction
  //

  inline
  access::object_traits< ::atccsinstruction >::id_type
  access::object_traits< ::atccsinstruction >::
  id (const object_type& o)
  {
    return o._id;
  }
}

namespace odb
{
  // atccsinstruction
  //
}

