// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "atccsguidescopestatus-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // atccsguidescopestatus
  //

  bool access::object_traits_impl< ::atccsguidescopestatus, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // atccspublicstatus base
    //
    if (object_traits_impl< ::atccspublicstatus, id_pgsql >::grow (
          i, t + 0UL))
      grew = true;

    // _indexOfCover
    //
    t[8UL] = 0;

    // _targetIndexeOfCover
    //
    t[9UL] = 0;

    // _positionOfCover
    //
    t[10UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::atccsguidescopestatus, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // atccspublicstatus base
    //
    object_traits_impl< ::atccspublicstatus, id_pgsql >::bind (b + n, i, sk);
    n += sk == statement_select ? 8UL : 7UL;

    // _indexOfCover
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i._indexOfCover_value;
    b[n].is_null = &i._indexOfCover_null;
    n++;

    // _targetIndexeOfCover
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i._targetIndexeOfCover_value;
    b[n].is_null = &i._targetIndexeOfCover_null;
    n++;

    // _positionOfCover
    //
    b[n].type = pgsql::bind::double_;
    b[n].buffer = &i._positionOfCover_value;
    b[n].is_null = &i._positionOfCover_null;
    n++;
  }

  bool access::object_traits_impl< ::atccsguidescopestatus, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // atccspublicstatus base
    //
    if (object_traits_impl< ::atccspublicstatus, id_pgsql >::init (i, o, sk))
      grew = true;

    // _indexOfCover
    //
    {
      short unsigned int const& v =
        o._indexOfCover;

      bool is_null (false);
      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_image (
        i._indexOfCover_value, is_null, v);
      i._indexOfCover_null = is_null;
    }

    // _targetIndexeOfCover
    //
    {
      short unsigned int const& v =
        o._targetIndexeOfCover;

      bool is_null (false);
      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_image (
        i._targetIndexeOfCover_value, is_null, v);
      i._targetIndexeOfCover_null = is_null;
    }

    // _positionOfCover
    //
    {
      double const& v =
        o._positionOfCover;

      bool is_null (false);
      pgsql::value_traits<
          double,
          pgsql::id_double >::set_image (
        i._positionOfCover_value, is_null, v);
      i._positionOfCover_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::atccsguidescopestatus, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // atccspublicstatus base
    //
    object_traits_impl< ::atccspublicstatus, id_pgsql >::init (o, i, db);

    // _indexOfCover
    //
    {
      short unsigned int& v =
        o._indexOfCover;

      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_value (
        v,
        i._indexOfCover_value,
        i._indexOfCover_null);
    }

    // _targetIndexeOfCover
    //
    {
      short unsigned int& v =
        o._targetIndexeOfCover;

      pgsql::value_traits<
          short unsigned int,
          pgsql::id_smallint >::set_value (
        v,
        i._targetIndexeOfCover_value,
        i._targetIndexeOfCover_null);
    }

    // _positionOfCover
    //
    {
      double& v =
        o._positionOfCover;

      pgsql::value_traits<
          double,
          pgsql::id_double >::set_value (
        v,
        i._positionOfCover_value,
        i._positionOfCover_null);
    }
  }
}

#include <odb/post.hxx>
