// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ATCCSUTILIZATION_ODB_HXX
#define ATCCSUTILIZATION_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "atccsutilization.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // atccsutilization
  //
  template <>
  struct class_traits< ::atccsutilization >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::atccsutilization >
  {
    public:
    typedef ::atccsutilization object_type;
    typedef ::atccsutilization* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // atccsutilization
  //
  template <typename A>
  struct query_columns< ::atccsutilization, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    at_type_;

    static const at_type_ at;

    // start
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    start_type_;

    static const start_type_ start;

    // end
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    end_type_;

    static const end_type_ end;

    // user
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    user_type_;

    static const user_type_ user;

    // plan
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    plan_type_;

    static const plan_type_ plan;

    // occupation
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    occupation_type_;

    static const occupation_type_ occupation;

    // priority
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    priority_type_;

    static const priority_type_ priority;

    // descirption
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    descirption_type_;

    static const descirption_type_ descirption;
  };

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::id_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::at_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  at (A::table_name, "\"at\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::start_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  start (A::table_name, "\"start\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::end_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  end (A::table_name, "\"end\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::user_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  user (A::table_name, "\"user\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::plan_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  plan (A::table_name, "\"plan\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::occupation_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  occupation (A::table_name, "\"occupation\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::priority_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  priority (A::table_name, "\"priority\"", 0);

  template <typename A>
  const typename query_columns< ::atccsutilization, id_pgsql, A >::descirption_type_
  query_columns< ::atccsutilization, id_pgsql, A >::
  descirption (A::table_name, "\"descirption\"", 0);

  template <typename A>
  struct pointer_query_columns< ::atccsutilization, id_pgsql, A >:
    query_columns< ::atccsutilization, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::atccsutilization, id_pgsql >:
    public access::object_traits< ::atccsutilization >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // _id
      //
      int _id_value;
      bool _id_null;

      // _at
      //
      int _at_value;
      bool _at_null;

      // _start
      //
      int _start_value;
      bool _start_null;

      // _end
      //
      int _end_value;
      bool _end_null;

      // _user
      //
      int _user_value;
      bool _user_null;

      // _plan
      //
      int _plan_value;
      bool _plan_null;

      // _occupation
      //
      int _occupation_value;
      bool _occupation_null;

      // _priority
      //
      int _priority_value;
      bool _priority_null;

      // _descirption
      //
      details::buffer _descirption_value;
      std::size_t _descirption_size;
      bool _descirption_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::atccsutilization, id_common >:
    public access::object_traits_impl< ::atccsutilization, id_pgsql >
  {
  };

  // atccsutilization
  //
}

#include "atccsutilization-odb.ixx"

#include <odb/post.hxx>

#endif // ATCCSUTILIZATION_ODB_HXX
