// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef CSREALTIMEDATA_ODB_HXX
#define CSREALTIMEDATA_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "csrealtimedata.h"

#include "emerealtimedata-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // csrealtimedata
  //
  template <>
  struct class_traits< ::csrealtimedata >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::csrealtimedata >
  {
    public:
    typedef ::csrealtimedata object_type;
    typedef ::csrealtimedata* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef object_traits< ::emerealtimedata >::id_type id_type;

    static const bool auto_id = object_traits< ::emerealtimedata >::auto_id;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // csrealtimedata
  //
  template <typename A>
  struct query_columns< ::csrealtimedata, id_pgsql, A >:
    query_columns< ::emerealtimedata, id_pgsql, A >
  {
    // emerealtimedata
    //
    typedef query_columns< ::emerealtimedata, id_pgsql, A > emerealtimedata;

    // relskytemperature
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    relskytemperature_type_;

    static const relskytemperature_type_ relskytemperature;

    // ambienttemperature
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    ambienttemperature_type_;

    static const ambienttemperature_type_ ambienttemperature;

    // sensortemperature
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    sensortemperature_type_;

    static const sensortemperature_type_ sensortemperature;

    // rainfall
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    rainfall_type_;

    static const rainfall_type_ rainfall;

    // rainthresh
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    rainthresh_type_;

    static const rainthresh_type_ rainthresh;

    // wind
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    wind_type_;

    static const wind_type_ wind;

    // windunits
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        short unsigned int,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    windunits_type_;

    static const windunits_type_ windunits;

    // humiditypercent
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    humiditypercent_type_;

    static const humiditypercent_type_ humiditypercent;

    // dewpoint
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    dewpoint_type_;

    static const dewpoint_type_ dewpoint;

    // daylight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    daylight_type_;

    static const daylight_type_ daylight;
  };

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::relskytemperature_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  relskytemperature (A::table_name, "\"relskytemperature\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::ambienttemperature_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  ambienttemperature (A::table_name, "\"ambienttemperature\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::sensortemperature_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  sensortemperature (A::table_name, "\"sensortemperature\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::rainfall_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  rainfall (A::table_name, "\"rainfall\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::rainthresh_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  rainthresh (A::table_name, "\"rainthresh\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::wind_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  wind (A::table_name, "\"wind\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::windunits_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  windunits (A::table_name, "\"windunits\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::humiditypercent_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  humiditypercent (A::table_name, "\"humiditypercent\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::dewpoint_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  dewpoint (A::table_name, "\"dewpoint\"", 0);

  template <typename A>
  const typename query_columns< ::csrealtimedata, id_pgsql, A >::daylight_type_
  query_columns< ::csrealtimedata, id_pgsql, A >::
  daylight (A::table_name, "\"daylight\"", 0);

  template <typename A>
  struct pointer_query_columns< ::csrealtimedata, id_pgsql, A >:
    query_columns< ::csrealtimedata, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::csrealtimedata, id_pgsql >:
    public access::object_traits< ::csrealtimedata >
  {
    public:
    typedef object_traits_impl< ::emerealtimedata, id_pgsql >::id_image_type id_image_type;

    struct image_type: object_traits_impl< ::emerealtimedata, id_pgsql >::image_type
    {
      // _relskytemperature
      //
      double _relskytemperature_value;
      bool _relskytemperature_null;

      // _ambienttemperature
      //
      double _ambienttemperature_value;
      bool _ambienttemperature_null;

      // _sensortemperature
      //
      double _sensortemperature_value;
      bool _sensortemperature_null;

      // _rainfall
      //
      short _rainfall_value;
      bool _rainfall_null;

      // _rainthresh
      //
      short _rainthresh_value;
      bool _rainthresh_null;

      // _wind
      //
      double _wind_value;
      bool _wind_null;

      // _windunits
      //
      short _windunits_value;
      bool _windunits_null;

      // _humiditypercent
      //
      double _humiditypercent_value;
      bool _humiditypercent_null;

      // _dewpoint
      //
      double _dewpoint_value;
      bool _dewpoint_null;

      // _daylight
      //
      double _daylight_value;
      bool _daylight_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 13UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::csrealtimedata, id_common >:
    public access::object_traits_impl< ::csrealtimedata, id_pgsql >
  {
  };

  // csrealtimedata
  //
}

#include "csrealtimedata-odb.ixx"

#include <odb/post.hxx>

#endif // CSREALTIMEDATA_ODB_HXX
