#ifndef ATCCSPROTOCOL_GLOBAL_H
#define ATCCSPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ATCCSPROTOCOL_LIBRARY)
#  define ATCCSPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ATCCSPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ATCCSPROTOCOL_GLOBAL_H
